# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agents/v1/agents.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61gents/v1/agents.proto\x12\tagents.v1\"\x1a\n\x04Word\x12\x12\n\x04word\x18\x02 \x01(\tR\x04word\"\x0f\n\rSpeakResponse\"\xae\x01\n\x05\x41gent\x12.\n\x04type\x18\x01 \x01(\x0e\x32\x1a.agents.v1.Agent.AgentTypeR\x04type\x12\x0e\n\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\"Q\n\tAgentType\x12\x1a\n\x16\x41GENT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x41GENT_TYPE_HUMAN\x10\x01\x12\x12\n\x0e\x41GENT_TYPE_BOT\x10\x02\"\x9c\x01\n\x05\x45vent\x12.\n\x07message\x18\x01 \x01(\x0b\x32\x12.agents.v1.MessageH\x00R\x07message\x12Z\n\x17interaction_zone_update\x18\x02 \x01(\x0b\x32 .agents.v1.InteractionZoneUpdateH\x00R\x15interactionZoneUpdateB\x07\n\x05\x65vent\"A\n\x15InteractionZoneUpdate\x12(\n\x06\x61gents\x18\x01 \x03(\x0b\x32\x10.agents.v1.AgentR\x06\x61gents\"G\n\x0b\x41gentAction\x12.\n\x07message\x18\x01 \x01(\x0b\x32\x12.agents.v1.MessageH\x00R\x07messageB\x08\n\x06\x61\x63tion\"K\n\x07Message\x12&\n\x05\x61gent\x18\x01 \x01(\x0b\x32\x10.agents.v1.AgentR\x05\x61gent\x12\x18\n\x07\x63ontent\x18\x02 \x01(\tR\x07\x63ontent2J\n\x0c\x41gentService\x12:\n\x08Interact\x12\x10.agents.v1.Event\x1a\x16.agents.v1.AgentAction\"\x00(\x01\x30\x01\x32P\n\x16\x41gentAudioVideoService\x12\x36\n\x05Speak\x12\x0f.agents.v1.Word\x1a\x18.agents.v1.SpeakResponse\"\x00(\x01\x42\x9f\x01\n\rcom.agents.v1B\x0b\x41gentsProtoP\x01Z<github.com/tmc/the-gathering/internal/gen/agents/v1;agentsv1\xa2\x02\x03\x41XX\xaa\x02\tAgents.V1\xca\x02\tAgents\\V1\xe2\x02\x15\x41gents\\V1\\GPBMetadata\xea\x02\nAgents::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agents.v1.agents_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.agents.v1B\013AgentsProtoP\001Z<github.com/tmc/the-gathering/internal/gen/agents/v1;agentsv1\242\002\003AXX\252\002\tAgents.V1\312\002\tAgents\\V1\342\002\025Agents\\V1\\GPBMetadata\352\002\nAgents::V1'
  _globals['_WORD']._serialized_start=37
  _globals['_WORD']._serialized_end=63
  _globals['_SPEAKRESPONSE']._serialized_start=65
  _globals['_SPEAKRESPONSE']._serialized_end=80
  _globals['_AGENT']._serialized_start=83
  _globals['_AGENT']._serialized_end=257
  _globals['_AGENT_AGENTTYPE']._serialized_start=176
  _globals['_AGENT_AGENTTYPE']._serialized_end=257
  _globals['_EVENT']._serialized_start=260
  _globals['_EVENT']._serialized_end=416
  _globals['_INTERACTIONZONEUPDATE']._serialized_start=418
  _globals['_INTERACTIONZONEUPDATE']._serialized_end=483
  _globals['_AGENTACTION']._serialized_start=485
  _globals['_AGENTACTION']._serialized_end=556
  _globals['_MESSAGE']._serialized_start=558
  _globals['_MESSAGE']._serialized_end=633
  _globals['_AGENTSERVICE']._serialized_start=635
  _globals['_AGENTSERVICE']._serialized_end=709
  _globals['_AGENTAUDIOVIDEOSERVICE']._serialized_start=711
  _globals['_AGENTAUDIOVIDEOSERVICE']._serialized_end=791
# @@protoc_insertion_point(module_scope)
