# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agents/v1/game_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61gents/v1/game_service.proto\x12\tagents.v1\"T\n\x0fJoinGameRequest\x12\x17\n\x07game_id\x18\x01 \x01(\tR\x06gameId\x12\x1c\n\x07room_id\x18\x02 \x01(\tH\x00R\x06roomId\x88\x01\x01\x42\n\n\x08_room_id\"1\n\x10JoinGameResponse\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId2T\n\x0bGameService\x12\x45\n\x08JoinGame\x12\x1a.agents.v1.JoinGameRequest\x1a\x1b.agents.v1.JoinGameResponse\"\x00\x42\xa4\x01\n\rcom.agents.v1B\x10GameServiceProtoP\x01Z<github.com/tmc/the-gathering/internal/gen/agents/v1;agentsv1\xa2\x02\x03\x41XX\xaa\x02\tAgents.V1\xca\x02\tAgents\\V1\xe2\x02\x15\x41gents\\V1\\GPBMetadata\xea\x02\nAgents::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agents.v1.game_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.agents.v1B\020GameServiceProtoP\001Z<github.com/tmc/the-gathering/internal/gen/agents/v1;agentsv1\242\002\003AXX\252\002\tAgents.V1\312\002\tAgents\\V1\342\002\025Agents\\V1\\GPBMetadata\352\002\nAgents::V1'
  _globals['_JOINGAMEREQUEST']._serialized_start=43
  _globals['_JOINGAMEREQUEST']._serialized_end=127
  _globals['_JOINGAMERESPONSE']._serialized_start=129
  _globals['_JOINGAMERESPONSE']._serialized_end=178
  _globals['_GAMESERVICE']._serialized_start=180
  _globals['_GAMESERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
