// @generated by protoc-gen-connect-es v1.1.2 with parameter "target=ts"
// @generated from file agents/v1/agents.proto (package agents.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GameEvent, HealthCheckRequest, HealthCheckResponse, PlayerEvent, ProvisionAgentRequest, ProvisionAgentResponse } from "./agents_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service agents.v1.AgentService
 */
export const AgentService = {
  typeName: "agents.v1.AgentService",
  methods: {
    /**
     * Interact is a bidirectional stream of agent actions and events.
     *
     * @generated from rpc agents.v1.AgentService.Interact
     */
    interact: {
      name: "Interact",
      I: PlayerEvent,
      O: GameEvent,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * @generated from rpc agents.v1.AgentService.HealthCheck
     */
    healthCheck: {
      name: "HealthCheck",
      I: HealthCheckRequest,
      O: HealthCheckResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agents.v1.AgentService.ProvisionAgent
     */
    provisionAgent: {
      name: "ProvisionAgent",
      I: ProvisionAgentRequest,
      O: ProvisionAgentResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

