// @generated by protoc-gen-connect-es v1.1.2 with parameter "target=ts"
// @generated from file agents/v1/game_service.proto (package agents.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { JoinGameRequest, JoinGameResponse } from "./game_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service agents.v1.GameService
 */
export const GameService = {
  typeName: "agents.v1.GameService",
  methods: {
    /**
     * @generated from rpc agents.v1.GameService.JoinGame
     */
    joinGame: {
      name: "JoinGame",
      I: JoinGameRequest,
      O: JoinGameResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

